In [1]:
import pandas as pd
import json

df = pd.read_csv("../dataset_comparative_2020_2026/comparative_files/keywords_yake_meta.csv")
print(f"Документів: {len(df):,}")
print(df.columns.tolist())
df.head(100)

Документів: 8,427
['doc_id', 'length', 'rubric', 'outcome', 'num_stages', 'main_committee', 'card_id', 'reg_num', 'reg_date', 'keywords_yake', 'num_keywords']

,doc_id,length,rubric,outcome,num_stages,main_committee,card_id,reg_num,reg_date,keywords_yake,num_keywords
0,12273_Порівняльна таблиця (04.12.2024),172,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45350,12273,2024-12-02,"[""Державний бюджет"", ""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ""В...",5
1,12272_Порівняльна таблиця (04.12.2024),376,Економічна політика,in_progress,4,Підласа Р. А. Комітет Верховної Ради України з...,45328,12272,2024-12-02,"[""Автономної Республіки"", ""Республіки Крим"", ""...",5
2,12274_Порівняльна таблиця (03.12.2024),145,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45349,12274,2024-12-02,"[""Державний бюджет"", ""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ""В...",5
3,12275_Порівняльна таблиця (04.12.2024),476,Безпека і оборона,in_progress,4,Завітневич О. М. Комітет Верховної Ради Україн...,45341,12275,2024-12-02,"[""військову службу"", ""Закону України"", ""ПОРІВН...",5
4,12276_Порівняльна таблиця (04.12.2024),499,Економічна політика,in_progress,4,Гетманцев Д. О. Комітет Верховної Ради України...,45363,12276,2024-12-02,"[""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ""проекту Закону"", ""лік...",5
...,...,...,...,...,...,...,...,...,...,...,...
95,12367-3_Порівняльна таблиця (14.01.2025),2718,Правова політика,in_progress,7,Іонушас С. К. Комітет Верховної Ради України з...,55616,12367-3,2025-01-14,"[""досудового розслідування"", ""кримінального пр...",27
96,12367_Порівняльна таблиця (31.12.2024),2100,Правова політика,rejected,8,Іонушас С. К. Комітет Верховної Ради України з...,55533,12367,2024-12-30,"[""досудового розслідування"", ""кодексу"", ""ПОРІВ...",21
97,12368-1_Порівняльна таблиця (07.01.2025),3852,Правова політика,in_progress,20,Маслов Д. В. Комітет Верховної Ради України з ...,55553,12368-1,2025-01-07,"[""України"", ""суду"", ""адміністративного суду"", ...",38
98,12353_Порівняльна таблиця (Друге читання),27351,Галузевий розвиток,in_progress,16,Бондаренко О. В. Комітет Верховної Ради Україн...,55504,12353,2024-12-23,"[""Міністрів України"", ""Кабінетом Міністрів"", ""...",50
99,12369_Порівняльна таблиця (31.12.2024),754,Соціальна політика,in_progress,4,Третьякова Г. М. Комітет Верховної Ради Україн...,55537,12369,2024-12-30,"[""дитинства підгрупи"", ""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ...",7

In [2]:
from collections import Counter

all_kw = []
for kw_json in df["keywords_yake"]:
    try:
        kw_list = json.loads(kw_json)
        all_kw.extend([kw.lower().strip() for kw in kw_list])
    except:
        pass

counter = Counter(all_kw)
print(f"Унікальних KW: {len(counter):,}")
print(f"Всього KW: {len(all_kw):,}")

Унікальних KW: 18,018
Всього KW: 176,349

In [3]:
from collections import defaultdict
import json

# Підрахунок document frequency
doc_freq = defaultdict(int)

for kw_json in df["keywords_yake"]:

    try:
        kw_list = json.loads(kw_json)

        # унікальні KW в межах одного документа
        unique_kw = set(
            kw.lower().strip()
            for kw in kw_list
        )

        for kw in unique_kw:
            doc_freq[kw] += 1

    except:
        pass

total_docs = len(df)

print(f"Всього документів: {total_docs}\n")

print(f"{'KW':<40} {'DF':>6} {'DF%':>7}")
print("-" * 60)

for kw, df_count in sorted(
    doc_freq.items(),
    key=lambda x: -x[1]
):

    pct = df_count / total_docs * 100

    print(
        f"{kw:<40} "
        f"{df_count:>6} "
        f"{pct:>6.1f}%"
    )

Всього документів: 8427

KW                                           DF     DF%
------------------------------------------------------------
порівняльна таблиця                        5948   70.6%
україни                                    5009   59.4%
закону україни                             4465   53.0%
міністрів україни                          2456   29.1%
ради україни                               2006   23.8%
зміст положення                            1947   23.1%
стаття                                     1944   23.1%
закону                                     1825   21.7%
верховної ради                             1674   19.9%
законом україни                            1551   18.4%
закон україни                              1426   16.9%
чинна редакція                             1240   14.7%
кабінетом міністрів                        1129   13.4%
статті                                     1079   12.8%
кодексу україни                            1005   11.9%
проекту закону                              881   10.5%
відомості верховної                         864   10.3%
проекту висновки                            847   10.1%
обґрунтування законопроект                  822    9.8%
законом                                     821    9.7%
читанні пропозиції                          818    9.7%
редакція                                    786    9.3%
пропозиції                                  774    9.2%
висновки                                    766    9.1%
законопроект                                742    8.8%
редакція редакція                           722    8.6%
законодавства зміст                         694    8.2%
виконавчої влади                            661    7.8%
осіб                                        644    7.6%
відхилено                                   640    7.6%
президента україни                          640    7.6%
кодексу                                     630    7.5%
території україни                           616    7.3%
міністрів                                   594    7.0%
редакції                                    588    7.0%
ради                                        580    6.9%
враховано                                   575    6.8%
державного                                  538    6.4%
особи                                       532    6.3%
україни реєстраційний                       511    6.1%
остаточній редакції                         497    5.9%
сфері                                       474    5.6%
зміст відповідного                          466    5.5%
законі україни                              464    5.5%
щодо                                        443    5.3%
україни щодо                                413    4.9%
державної                                   410    4.9%
першому читанні                             393    4.7%
сил україни                                 385    4.6%
україни стаття                              381    4.5%
влади                                       381    4.5%
законів україни                             372    4.4%
кабінету міністрів                          371    4.4%
такій редакції                              352    4.2%
головним комітетом                          349    4.1%
запропонований головним                     348    4.1%
радою україни                               347    4.1%
виконавчої                                  342    4.1%
республіки крим                             316    3.7%
безпеки україни                             312    3.7%
автономної республіки                       307    3.6%
бюджету україни                             305    3.6%
разі                                        301    3.6%
територію україни                           289    3.4%
розділу                                     288    3.4%
діяльності                                  287    3.4%
пункту                                      279    3.3%
державного бюджету                          272    3.2%
відхилено абзац                             271    3.2%
служби                                      271    3.2%
рішення                                     267    3.2%
оборони україни                             262    3.1%
реалізує державну                           258    3.1%
верховної                                   258    3.1%
перехідні положення                         255    3.0%
відповідно                                  253    3.0%
частини                                     253    3.0%
служби україни                              249    3.0%
кабінетом                                   247    2.9%
податку                                     246    2.9%
суду                                        245    2.9%
російської федерації                        242    2.9%
воєнного стану                              235    2.8%
освіти                                      230    2.7%
доходів громадян                            228    2.7%
законодавства україни                       218    2.6%
конституції україни                         217    2.6%
проведення                                  216    2.6%
державну політику                           215    2.6%
мінімумів доходів                           213    2.5%
місцевого самоврядування                    212    2.5%
кодекс україни                              209    2.5%
органу                                      206    2.4%
зміст                                       203    2.4%
збройних сил                                200    2.4%
забезпечення                                199    2.4%
національного                               195    2.3%
податкового кодексу                         193    2.3%
військової служби                           192    2.3%
строк                                       190    2.3%
охорони                                     183    2.2%
адміністративні правопорушення              182    2.2%
послуг                                      180    2.1%
україні                                     179    2.1%
абзац                                       179    2.1%
реєстру                                     178    2.1%
неоподатковуваних мінімумів                 177    2.1%
фонду                                       175    2.1%
проєкту закону                              172    2.0%
органу виконавчої                           172    2.0%
комісії                                     172    2.0%
державну                                    171    2.0%
державний бюджет                            169    2.0%
вищої                                       168    2.0%
рада україни                                168    2.0%
банку україни                               167    2.0%
право                                       163    1.9%
фонду державного                            162    1.9%
засобів                                     161    1.9%
відсутня стаття                             159    1.9%
громадян                                    158    1.9%
майна                                       157    1.9%
права                                       157    1.9%
президентом україни                         157    1.9%
такого змісту                               155    1.8%
положення                                   155    1.8%
враховано частково                          154    1.8%
законами україни                            153    1.8%
проекту                                     153    1.8%
кабінет міністрів                           152    1.8%
правопорушення                              151    1.8%
доходів                                     150    1.8%
провадження                                 149    1.8%
частиною                                    149    1.8%
військову службу                            148    1.8%
кримінального кодексу                       146    1.7%
національної                                146    1.7%
кодексом україни                            146    1.7%
суду україни                                145    1.7%
безпеки                                     144    1.7%
державного реєстру                          144    1.7%
власності                                   143    1.7%
відхилено пункт                             142    1.7%
юридичної особи                             142    1.7%
органів                                     142    1.7%
доповнити                                   141    1.7%
порядку                                     140    1.7%
єдиного                                     138    1.6%
сфері охорони                               138    1.6%
вищої освіти                                136    1.6%
бюро україни                                136    1.6%
інвалідністю                                135    1.6%
запропонована редакція                      135    1.6%
бюджет україни                              135    1.6%
кримінального                               133    1.6%
обґрунтування                               132    1.6%
другою статті                               132    1.6%
третьою статті                              131    1.6%
редакція запропонована                      131    1.6%
господарювання                              130    1.5%
враховано редакційно                        129    1.5%
укт зед                                     129    1.5%
органом виконавчої                          129    1.5%
виконання                                   128    1.5%
громадян україни                            126    1.5%
стану                                       126    1.5%
податкового                                 126    1.5%
надання                                     125    1.5%
першою статті                               124    1.5%
статтями                                    124    1.5%
відхилено виключити                         124    1.5%
земельних ділянок                           122    1.4%
україни відповідно                          121    1.4%
військової                                  121    1.4%
позбавленням волі                           119    1.4%
захисту                                     119    1.4%
політику                                    119    1.4%
банком україни                              119    1.4%
транспортних засобів                        119    1.4%
території                                   117    1.4%
електричної енергії                         117    1.4%
накладення штрафу                           117    1.4%
управління                                  117    1.4%
охорони здоров’я                            117    1.4%
порушення                                   115    1.4%
прав                                        114    1.4%
товарів                                     113    1.3%
організації                                 112    1.3%
викласти                                    112    1.3%
фізичних осіб                               112    1.3%
воєнного                                    112    1.3%
суддів україни                              111    1.3%
депутати україни                            111    1.3%
єдиного державного                          111    1.3%
енергії                                     111    1.3%
допомоги                                    110    1.3%
земельної ділянки                           110    1.3%
крим                                        110    1.3%
використання                                109    1.3%
актів україни                               109    1.3%
інформації                                  109    1.3%
реалізує                                    109    1.3%
продукції                                   109    1.3%
електронних                                 108    1.3%
державної служби                            108    1.3%
користування                                108    1.3%
волі                                        107    1.3%
договору                                    107    1.3%
державної реєстрації                        107    1.3%
місцевого                                   106    1.3%
оподаткування                               106    1.3%
частиною першою                             105    1.2%
російської                                  105    1.2%
федерації                                   105    1.2%
забезпечує формування                       104    1.2%
державної політики                          104    1.2%
мінімумів                                   103    1.2%
такого                                      101    1.2%
тютюнових виробів                           101    1.2%
вищої ради                                  101    1.2%
інформації україни                          101    1.2%
земельних                                   101    1.2%
силах україни                               100    1.2%
виключити                                    99    1.2%
україни шмигаль                              97    1.2%
відхилено частину                            97    1.2%
збройних                                     96    1.1%
ринку                                        96    1.1%
дітей                                        96    1.1%
системи                                      96    1.1%
законодавством україни                       95    1.1%
банк україни                                 94    1.1%
дії                                          94    1.1%
законопроекту                                94    1.1%
враховано абзац                              93    1.1%
природного                                   92    1.1%
здійснення                                   92    1.1%
бюджету                                      92    1.1%
неоподатковуваних                            91    1.1%
законодавства                                91    1.1%
ділянки                                      91    1.1%
національного банку                          90    1.1%
національного агентства                      90    1.1%
бюро                                         90    1.1%
страхування                                  89    1.1%
четвертою статті                             89    1.1%
здоров’я                                     89    1.1%
частиною другою                              88    1.0%
судді                                        88    1.0%
електричної                                  88    1.0%
центрального органу                          87    1.0%
населення                                    87    1.0%
дитини                                       87    1.0%
верховною радою                              87    1.0%
суд                                          86    1.0%
самоврядування                               86    1.0%
республіки                                   86    1.0%
такій                                        85    1.0%
президент україни                            85    1.0%
пункт                                        83    1.0%
норма відсутня                               83    1.0%
призначення                                  82    1.0%
акта закон                                   82    1.0%
судового                                     82    1.0%
частини першої                               81    1.0%
агресії російської                           81    1.0%
податковий кодекс                            81    1.0%
комітету україни                             81    1.0%
виробів                                      80    0.9%
справи                                       80    0.9%
майна україни                                80    0.9%
відомості                                    79    0.9%
міністрів автономної                         79    0.9%
конкурсної комісії                           79    0.9%
замінити                                     79    0.9%
сил                                          78    0.9%
період                                       78    0.9%
реєстрації                                   78    0.9%
національної безпеки                         78    0.9%
єдиного податку                              78    0.9%
заходів                                      78    0.9%
службу                                       77    0.9%
фонду україни                                77    0.9%
автономної                                   77    0.9%
замінити словами                             77    0.9%
заробітної плати                             77    0.9%
природного газу                              76    0.9%
сфері освіти                                 76    0.9%
української рср                              76    0.9%
числі                                        75    0.9%
закладів                                     75    0.9%
суддів                                       75    0.9%
відповідного положення                       75    0.9%
єдиного внеску                               75    0.9%
юридичної                                    75    0.9%
юстиції україни                              75    0.9%
розвитку                                     74    0.9%
громадянина україни                          74    0.9%
кримінального провадження                    74    0.9%
перша статті                                 74    0.9%
податків                                     74    0.9%
слова                                        74    0.9%
конституцією україни                         74    0.9%
тютюнових                                    73    0.9%
дня                                          73    0.9%
контролю                                     73    0.9%
національного бюро                           72    0.9%
плати                                        72    0.9%
платника податку                             72    0.9%
посадових осіб                               72    0.9%
лікарських засобів                           71    0.8%
частина                                      71    0.8%
земельної                                    71    0.8%
конституційного суду                         70    0.8%
європейського союзу                          70    0.8%
транспортних                                 70    0.8%
цивільного захисту                           70    0.8%
президента                                   69    0.8%
україни військових                           69    0.8%
соціального                                  69    0.8%
кордон україни                               69    0.8%
словами                                      69    0.8%
ради автономної                              68    0.8%
україни пропозиції                           68    0.8%
прикінцеві положення                         68    0.8%
акта пояснення                               68    0.8%
навчання                                     67    0.8%
директора національного                      67    0.8%
банку                                        67    0.8%
ради правосуддя                              67    0.8%
охорони україни                              67    0.8%
ділянок                                      67    0.8%
національної поліції                         66    0.8%
служби безпеки                               66    0.8%
судового рішення                             66    0.8%
позбавленням                                 65    0.8%
проживання                                   65    0.8%
середньої освіти                             65    0.8%
першої статті                                64    0.8%
внесення змін                                64    0.8%
відхилено підпункт                           64    0.8%
соціального захисту                          64    0.8%
прожиткового мінімуму                        64    0.8%
дії воєнного                                 64    0.8%
виробництва                                  64    0.8%
бюджетного кодексу                           64    0.8%
змісту                                       63    0.7%
першому                                      63    0.7%
зед                                          63    0.7%
укт                                          63    0.7%
страхування україни                          63    0.7%
питань                                       62    0.7%
послуги                                      62    0.7%
україни має                                  62    0.7%

In [4]:
from collections import defaultdict
import json

total_freq = defaultdict(int)

for kw_json in df["keywords_yake"]:

    try:
        kw_list = json.loads(kw_json)

        for kw in kw_list:

            kw = kw.lower().strip()

            if kw:
                total_freq[kw] += 1

    except:
        pass

In [5]:
rubric_kw_freq = {}

for rubric, group in df.groupby("rubric"):

    temp_freq = defaultdict(int)

    for kw_json in group["keywords_yake"]:

        try:
            kw_list = json.loads(kw_json)

            # унікальні KW в межах документа
            unique_kw = set(
                kw.lower().strip()
                for kw in kw_list
            )

            for kw in unique_kw:
                temp_freq[kw] += 1

        except:
            pass

    rubric_kw_freq[rubric] = sorted(
        temp_freq.items(),
        key=lambda x: -x[1]
    )[:20]

# ВИВІД ТОП-KW ПО РУБРИКАХ

for rubric, keywords in rubric_kw_freq.items():

    print(f"\n{rubric} ")
    print(f"{'KW':<40} {'DF':>6}")
    print("-" * 50)

    for kw, count in keywords:
        print(f"{kw:<40} {count:>6}")

Безпека і оборона
KW                                           DF
--------------------------------------------------
закону україни                              394
порівняльна таблиця                         384
україни                                     375
міністрів україни                           178
сил україни                                 171
верховної ради                              170
ради україни                                159
закон україни                               143
збройних сил                                129
закону                                      119
зміст положення                             119
служби                                      117
оборони україни                             115
відомості верховної                         114
військової служби                           113
військову службу                            111
законом україни                              99
президента україни                           94
безпеки україни                              91
законів україни                              79

Галузевий розвиток
KW                                           DF
--------------------------------------------------
порівняльна таблиця                        1176
україни                                    1158
закону україни                             1020
міністрів україни                           807
стаття                                      541
закону                                      540
ради україни                                444
закон україни                               416
кабінетом міністрів                         386
законом україни                             384
зміст положення                             382
виконавчої влади                            347
верховної ради                              311
сфері                                       294
проекту висновки                            270
читанні пропозиції                          264
обґрунтування законопроект                  264
редакція                                    257
висновки                                    255
пропозиції                                  254

Гуманітарна політика
KW                                           DF
--------------------------------------------------
порівняльна таблиця                         234
україни                                     148
закону україни                              148
зміст положення                              98
міністрів україни                            86
ради україни                                 61
закону                                       61
верховної ради                               60
законом україни                              60
освіти                                       56
закон україни                                56
стаття                                       54
чинна редакція                               45
кабінетом міністрів                          42
законом                                      42
виконавчої влади                             40
проекту закону                               38
вищої освіти                                 38
сфері                                        37
відомості верховної                          36

Державне будівництво
KW                                           DF
--------------------------------------------------
порівняльна таблиця                         344
україни                                     318
закону україни                              268
ради україни                                226
верховної ради                              216
міністрів україни                           182
ради                                        153
стаття                                      120
законом україни                             112
закону                                      107
зміст положення                              94
закон україни                                92
президента україни                           90
кабінетом міністрів                          86
чинна редакція                               76
міністрів                                    76
кабінету міністрів                           71
верховної                                    65
законом                                      62
республіки крим                              59

Економічна політика
KW                                           DF
--------------------------------------------------
порівняльна таблиця                        1640
україни                                    1489
закону україни                             1278
міністрів україни                           652
зміст положення                             598
закону                                      498
ради україни                                466
кодексу україни                             459
стаття                                      433
законом україни                             430
верховної ради                              366
чинна редакція                              351
кодексу                                     336
закон україни                               310
проекту закону                              309
статті                                      307
території україни                           269
законодавства зміст                         259
кабінетом міністрів                         258
бюджету україни                             249

Організаційні питання
KW                                           DF
--------------------------------------------------
верховної ради                               43
ради україни                                 42
слуга народу                                 21
постанови верховної                          20
політичної партії                            18
фракція політичної                           16
порівняльна таблиця                          11
україни                                       8
ради                                          6
чинна редакція                                5
верховної                                     4
російської федерації                          3
тимчасової слідчої                            3
постанова верховної                           3
редакція редакція                             3
ної партії                                    3
україни дев’ятого                             3
законодавче забезпечення                      3
законодавства україни                         2
україни щодо                                  2

Правова політика
KW                                           DF
--------------------------------------------------
порівняльна таблиця                        1621
україни                                    1100
закону україни                              910
стаття                                      553
ради україни                                494
зміст положення                             467
статті                                      418
верховної ради                              389
чинна редакція                              357
кодексу україни                             346
законом україни                             322
міністрів україни                           270
закону                                      266
закон україни                               256
проекту закону                              251
суду                                        227
особи                                       223
кодексу                                     222
законом                                     219
доходів громадян                            200

Соціальна політика
KW                                           DF
--------------------------------------------------
порівняльна таблиця                         535
закону україни                              446
україни                                     411
міністрів україни                           281
закону                                      234
кабінетом міністрів                         204
зміст положення                             189
стаття                                      175
закон україни                               153
законом україни                             143
осіб                                        125
статті                                      118
верховної ради                              115
чинна редакція                              112
ради україни                                110
міністрів                                   103
редакція редакція                            96
законом                                      85
інвалідністю                                 81
відомості верховної                          77

Установчі повноваження
KW                                           DF
--------------------------------------------------
ради україни                                  4
верховної ради                                4
порівняльна таблиця                           3
україни                                       2
конституції україни                           2
рада україни                                  2
стипендій верховної                           2
верховна рада                                 2
луганської областей                           1
вибори депутатів                              1
законом україни                               1
республіки крим                               1
луганській областях                           1
автономної республіки                         1
діюча редакція                                1
закону україни                                1
ради                                          1
верховної                                     1

In [6]:
### ФІЛЬТРАЦІЯ

In [7]:
from pathlib import Path
from collections import defaultdict
import pandas as pd
import json

In [8]:
BASE_DIR = Path("../dataset_comparative_2020_2026")
OUTPUT_DIR = BASE_DIR / "comparative_files" / "keywords_yake_filtred"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

In [9]:
df_original = df.copy()

total_docs = len(df_original)

print(f"Всього документів: {total_docs:,}")
print(df_original.columns.tolist())

Всього документів: 8,427
['doc_id', 'length', 'rubric', 'outcome', 'num_stages', 'main_committee', 'card_id', 'reg_num', 'reg_date', 'keywords_yake', 'num_keywords']

In [10]:
DF_THRESHOLD = 0.09

stopwords_9pct = {
    kw
    for kw, cnt in doc_freq.items()
    if cnt / total_docs > DF_THRESHOLD
}

print(f"Ключових слів, які зустрічаються більше ніж у 9% документів: {len(stopwords_9pct):,}")

Ключових слів, які зустрічаються більше ніж у 9% документів: 24

In [11]:
removed_keywords = []

for kw, cnt in sorted(doc_freq.items(), key=lambda x: -x[1]):
    if kw in stopwords_9pct:
        removed_keywords.append({
            "keyword": kw,
            "documents": cnt,
            "percent": round(cnt / total_docs * 100, 2)
        })

removed_keywords_df = pd.DataFrame(removed_keywords)

display(removed_keywords_df)

                       keyword  documents  percent
0          порівняльна таблиця       5948    70.58
1                      україни       5009    59.44
2               закону україни       4465    52.98
3            міністрів україни       2456    29.14
4                 ради україни       2006    23.80
5              зміст положення       1947    23.10
6                       стаття       1944    23.07
7                       закону       1825    21.66
8               верховної ради       1674    19.86
9              законом україни       1551    18.41
10               закон україни       1426    16.92
11              чинна редакція       1240    14.71
12         кабінетом міністрів       1129    13.40
13                      статті       1079    12.80
14             кодексу україни       1005    11.93
15              проекту закону        881    10.45
16         відомості верховної        864    10.25
17            проекту висновки        847    10.05
18  обґрунтування законопроект        822     9.75
19                     законом        821     9.74
20          читанні пропозиції        818     9.71
21                    редакція        786     9.33
22                  пропозиції        774     9.18
23                    висновки        766     9.09

In [12]:
def filter_keywords_9pct(kw_json):
    try:
        kw_list = json.loads(kw_json)

        filtered = [
            kw.lower().strip()
            for kw in kw_list
            if kw.lower().strip() not in stopwords_9pct
        ]

        return json.dumps(filtered, ensure_ascii=False)

    except:
        return json.dumps([], ensure_ascii=False)

In [13]:
df_keywords_filtered = df_original.copy()

df_keywords_filtered["keywords_yake_original"] = df_keywords_filtered["keywords_yake"]

df_keywords_filtered["keywords_yake"] = df_keywords_filtered["keywords_yake"].apply(
    filter_keywords_9pct
)

df_keywords_filtered["num_keywords_after_9pct_filter"] = df_keywords_filtered["keywords_yake"].apply(
    lambda x: len(json.loads(x)) if pd.notna(x) else 0
)

print("Середня кількість KW після фільтрації:")
print(round(df_keywords_filtered["num_keywords_after_9pct_filter"].mean(), 2))

display(df_keywords_filtered.head())

Середня кількість KW після фільтрації:
15.93

,doc_id,length,rubric,outcome,num_stages,main_committee,card_id,reg_num,reg_date,keywords_yake,num_keywords,keywords_yake_original,num_keywords_after_9pct_filter
0,12273_Порівняльна таблиця (04.12.2024),172,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45350,12273,2024-12-02,"[""державний бюджет"", ""закону зміст""]",5,"[""Державний бюджет"", ""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ""В...",2
1,12272_Порівняльна таблиця (04.12.2024),376,Економічна політика,in_progress,4,Підласа Р. А. Комітет Верховної Ради України з...,45328,12272,2024-12-02,"[""автономної республіки"", ""республіки крим""]",5,"[""Автономної Республіки"", ""Республіки Крим"", ""...",2
2,12274_Порівняльна таблиця (03.12.2024),145,Економічна політика,rejected,5,Підласа Р. А. Комітет Верховної Ради України з...,45349,12274,2024-12-02,"[""державний бюджет"", ""закону зміст""]",5,"[""Державний бюджет"", ""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ""В...",2
3,12275_Порівняльна таблиця (04.12.2024),476,Безпека і оборона,in_progress,4,Завітневич О. М. Комітет Верховної Ради Україн...,45341,12275,2024-12-02,"[""військову службу"", ""військової служби""]",5,"[""військову службу"", ""Закону України"", ""ПОРІВН...",2
4,12276_Порівняльна таблиця (04.12.2024),499,Економічна політика,in_progress,4,Гетманцев Д. О. Комітет Верховної Ради України...,45363,12276,2024-12-02,"[""лікарських засобів"", ""законодавства зміст""]",5,"[""ПОРІВНЯЛЬНА ТАБЛИЦЯ"", ""проекту Закону"", ""лік...",2

In [14]:
filtered_csv = OUTPUT_DIR / "keywords_yake_filtred.csv"
filtered_parquet = OUTPUT_DIR / "keywords_yake_filtred.parquet"

df_keywords_filtered.to_csv(filtered_csv, index=False, encoding="utf-8-sig")
df_keywords_filtered.to_parquet(filtered_parquet, index=False)

print("Збережено:")
print(filtered_csv)
print(filtered_parquet)

Збережено:
..\dataset_comparative_2020_2026\comparative_files\keywords_yake_filtred\keywords_yake_filtred.csv
..\dataset_comparative_2020_2026\comparative_files\keywords_yake_filtred\keywords_yake_filtred.parquet

In [18]:
from collections import defaultdict
import pandas as pd
import json

def get_top_keywords_by_documents(df_input, keywords_col="keywords_yake", top_n=30):
    doc_freq = defaultdict(int)
    total_docs = len(df_input)

    for kw_json in df_input[keywords_col]:
        try:
            kw_list = json.loads(kw_json)

            unique_kw = set(
                kw.lower().strip()
                for kw in kw_list
                if str(kw).strip()
            )

            for kw in unique_kw:
                doc_freq[kw] += 1

        except:
            pass

    rows = []

    for kw, cnt in sorted(doc_freq.items(), key=lambda x: -x[1])[:top_n]:
        rows.append({
            "keyword": kw,
            "documents": cnt,
            "percent_of_docs": round(cnt / total_docs * 100, 2)
        })

    return pd.DataFrame(rows)

In [16]:
top_before_filter_compare = top_before_filter.rename(columns={
    "keyword": "keyword_before",
    "documents": "documents_before",
    "percent_of_docs": "percent_before"
})

top_after_filter_compare = top_after_filter.rename(columns={
    "keyword": "keyword_after",
    "documents": "documents_after",
    "percent_of_docs": "percent_after"
})

top_keywords_before_after = pd.concat(
    [top_before_filter_compare, top_after_filter_compare],
    axis=1
)

display(top_keywords_before_after)

NameError: name 'top_before_filter' is not defined

In [ ]:
FILTER_STEPS = [0.02, 0.04, 0.06, 0.08, 0.10]

filtered_versions = {}

for p in FILTER_STEPS:

    threshold = df_keywords_filtered["length"].quantile(p)

    df_length_filtered = df_keywords_filtered[
        df_keywords_filtered["length"] > threshold
    ].copy()

    filter_name = f"without_shortest_{int(p * 100)}pct"
    filtered_versions[filter_name] = df_length_filtered

    csv_path = OUTPUT_DIR / f"keywords_yake_filtred_{int(p * 100)}pct.csv"
    parquet_path = OUTPUT_DIR / f"keywords_yake_filtred_{int(p * 100)}pct.parquet"

    df_length_filtered.to_csv(csv_path, index=False, encoding="utf-8-sig")
    df_length_filtered.to_parquet(parquet_path, index=False)

    print("-" * 60)
    print(f"Відкинуто найменші {int(p * 100)}% документів")
    print(f"Поріг length: {threshold:.2f}")
    print(f"Залишилось документів: {len(df_length_filtered):,}")
    print(f"Saved CSV     : {csv_path}")
    print(f"Saved Parquet : {parquet_path}")

In [ ]:
TOP_N = 20

comparison_data = {}

for dataset_name, current_df in datasets.items():

    doc_freq = defaultdict(int)

    for kw_json in current_df["keywords_yake"]:

        try:
            kw_list = json.loads(kw_json)

            unique_kw = set(
                kw.lower().strip()
                for kw in kw_list
            )

            for kw in unique_kw:
                doc_freq[kw] += 1

        except:
            pass

    total_docs = len(current_df)

    top_keywords = sorted(
        doc_freq.items(),
        key=lambda x: -x[1]
    )[:TOP_N]

    comparison_data[dataset_name] = [
        f"{kw} ({df_count}, {df_count/total_docs*100:.1f}%)"
        for kw, df_count in top_keywords
    ]

In [ ]:
datasets = {
    "df9_only": df_keywords_filtered,
    **filtered_versions
}

print("Доступні версії датасету:")

for name, dataset in datasets.items():
    print(f"{name:<30} {len(dataset):,} документів")

In [ ]:
TOP_N = 20

comparison_data = {}

for dataset_name, current_df in datasets.items():

    current_doc_freq = defaultdict(int)

    for kw_json in current_df["keywords_yake"]:

        try:
            kw_list = json.loads(kw_json)

            unique_kw = set(
                kw.lower().strip()
                for kw in kw_list
                if str(kw).strip()
            )

            for kw in unique_kw:
                current_doc_freq[kw] += 1

        except:
            pass

    current_total_docs = len(current_df)

    top_keywords = sorted(
        current_doc_freq.items(),
        key=lambda x: -x[1]
    )[:TOP_N]

    comparison_data[dataset_name] = [
        f"{kw} ({df_count}, {df_count / current_total_docs * 100:.1f}%)"
        for kw, df_count in top_keywords
    ]

comparison_df = pd.DataFrame(comparison_data)

display(comparison_df)

In [ ]:
stats = []

for dataset_name, current_df in datasets.items():
    keyword_counts = current_df["keywords_yake"].apply(
        lambda x: len(json.loads(x)) if pd.notna(x) else 0
    )

    stats.append({
        "dataset": dataset_name,
        "documents": len(current_df),
        "avg_keywords": round(keyword_counts.mean(), 2),
        "min_keywords": keyword_counts.min(),
        "max_keywords": keyword_counts.max(),
        "empty_keyword_docs": (keyword_counts == 0).sum()
    })

stats_df = pd.DataFrame(stats)

display(stats_df)

=== YAKE — кількість ключових слів з кожного файлу ===

NameError: name 'FILTER_STEPS' is not defined